version: "3.4"

services:
  api-shorten-url:
    build:
      context: .
      dockerfile: Dockerfile
    image: shorten/url
    volumes:
      - ./.env:/usr/src/app/.env
    ports:
      - "3080:3080"
